let dados = [
    {   
        titulo: 'Forrest Gump - O Contador de Histórias',
        descricao: "Forrest Gump - O Contador de Histórias é um filme de 1994 que conta a vida de Forrest Gump, um homem simples do Alabama, interpretado por Tom Hanks. Embora tenha um QI baixo, ele se envolve em eventos históricos significativos e impacta a vida de várias pessoas, tudo enquanto persegue seu amor de infância, Jenny. O filme é uma jornada emocional que mistura drama, comédia e romance, destacando temas como a inocência, o destino e a perseverança.",
        direcao: "Robert Zemeckis",
        Ano: "1994",
        Elenco: "Tom Hanks (Forrest Gump), Robin Wright (Jenny), Gary Sinise (Tenente Dan)",
        Roteiro: "Eric Roth (baseado no romance de Winston Groom)",
        Gênero: "Drama,Comédia,Romance",
        Duração: "2:36:00 (142 minutos)",
        Prêmios: "Vencedor de 6 Oscars, incluindo Melhor Filme, Melhor Diretor e Melhor Ator (Tom Hanks)",
        Bilheteria: "Mais de $678 milhões mundialmente",
        link: "https://en.wikipedia.org/wiki/Forrest_Gump",
        tags:"Forrest Gump, Tom Hanks, forest, Jenny, Bubba, Lieutenant Dan, Life is like a box of chocolates, Forrest running scene, Oscar-winning movie, 1994 film",
        rating: "4.7/5",
        imagem: "img/forrestgump.jpg"
    },
    {
        titulo: 'O Lobo de Wall Street',
        descricao: "O Lobo de Wall Street é um filme de 2013 baseado na história real de Jordan Belfort, um corretor da bolsa de valores em Nova York que construiu um império milionário usando métodos fraudulentos. O filme explora seu estilo de vida extravagante, seus excessos e eventual queda, oferecendo uma crítica ácida ao mundo corporativo e à ambição desenfreada.",
        direcao: "Martin Scorsese",
        Ano: "2013",
        Elenco: "Leonardo DiCaprio (Jordan Belfort), Jonah Hill (Donnie Azoff), Margot Robbie (Naomi Lapaglia), Matthew McConaughey (Mark Hanna)",
        Roteiro: "Terence Winter (baseado no livro de Jordan Belfort)",
        Gênero: "Biografia, Comédia, Crime",
        Duração: "3:00:00 (180 minutos)",
        Prêmios: "Indicado a 5 Oscars, incluindo Melhor Filme, Melhor Diretor (Martin Scorsese) e Melhor Ator (Leonardo DiCaprio)",
        Bilheteria: "Aproximadamente $392 milhões mundialmente",
        link: "https://www.imdb.com/title/tt0993846/",
        tags: "The Wolf of Wall Street, Leonardo DiCaprio, Jordan Belfort, Martin Scorsese, Jonah Hill, Wall Street, Stockbroker, Financial crime, Margot Robbie, Excess and debauchery, Stratton Oakmont, Belfort memoir, 2013 film, Oscar-nominated movie, Belfort yacht sinking scene",
        rating: "4.1/5",
        imagem: "img/olobodewallstreet.jpg"
    },
    {
        titulo: 'Titanic',
        descricao: "Titanic é um filme de 1997 dirigido por James Cameron, que conta a trágica história do naufrágio do RMS Titanic. O filme segue o romance entre Jack e Rose, dois passageiros de classes sociais diferentes, que lutam para sobreviver ao desastre. Titanic é amplamente aclamado por sua cinematografia, efeitos visuais e trilha sonora.",
        direcao: "James Cameron",
        Ano: "1997",
        Elenco: "Leonardo DiCaprio (Jack Dawson), Kate Winslet (Rose DeWitt Bukater), Billy Zane (Cal Hockley)",
        Roteiro: "James Cameron",
        Gênero: "Drama, Romance",
        Duração: "3:15:00 (195 minutos)",
        Prêmios: "Vencedor de 11 Oscars, incluindo Melhor Filme e Melhor Diretor",
        Bilheteria: "Mais de $2.2 bilhões mundialmente",
        link: "https://www.imdb.com/title/tt0120338/",
        tags: "Titanic, Leonardo DiCaprio, Kate Winslet, James Cameron, RMS Titanic, Romance, Drama, 1997 film, Oscar-winning movie, Epic film",
        rating: "4.4/5",
        imagem: "img/titanic.jpg"
    },
    {
        titulo: 'Avatar',
        descricao: "Avatar, lançado em 2009, é um filme de ficção científica dirigido por James Cameron. A história se passa no exuberante mundo de Pandora, onde os humanos estão extraindo recursos naturais e enfrentam os Na'vi, uma espécie nativa. O filme é conhecido por seus efeitos visuais revolucionários e se tornou o filme de maior bilheteria da história até 2019.",
        direcao: "James Cameron",
        Ano: "2009",
        Elenco: "Sam Worthington (Jake Sully), Zoe Saldana (Neytiri), Sigourney Weaver (Dr. Grace Augustine)",
        Roteiro: "James Cameron",
        Gênero: "Ficção Científica, Aventura",
        Duração: "2:42:00 (162 minutos)",
        Prêmios: "Vencedor de 3 Oscars, incluindo Melhor Direção de Arte e Melhores Efeitos Visuais",
        Bilheteria: "Mais de $2.8 bilhões mundialmente",
        link: "https://www.imdb.com/title/tt0499549/",
        tags: "Avatar, Pandora, James Cameron, Sam Worthington, Zoe Saldana, Na'vi, Sci-fi, 2009 film, Highest-grossing movie, Visual effects",
        rating: "4.2/5",
        imagem: "img/avatar.jpg"
    },
    {
        titulo: 'Vingadores: Ultimato',
        descricao: "Vingadores: Ultimato é o épico encerramento da saga do Infinito no Universo Cinematográfico Marvel, lançado em 2019. O filme segue os Vingadores restantes que tentam reverter os efeitos do estalo de Thanos. Dirigido pelos irmãos Russo, Ultimato quebrou recordes de bilheteria e se tornou um marco no cinema de super-heróis.",
        direcao: "Anthony Russo, Joe Russo",
        Ano: "2019",
        Elenco: "Robert Downey Jr. (Tony Stark), Chris Evans (Steve Rogers), Chris Hemsworth (Thor), Scarlett Johansson (Natasha Romanoff)",
        Roteiro: "Christopher Markus, Stephen McFeely",
        Gênero: "Ação, Aventura, Ficção Científica",
        Duração: "3:02:00 (182 minutos)",
        Prêmios: "Indicado a 1 Oscar de Melhores Efeitos Visuais",
        Bilheteria: "Mais de $2.7 bilhões mundialmente",
        link: "https://www.imdb.com/title/tt4154796/",
        tags: "Avengers, Endgame, Marvel, MCU, Thanos, Tony Stark, Superhero, Chris Evans, 2019 film, Blockbuster, Russo Brothers",
        rating: "4.3/5",
        imagem: "img/vingadores_ultimato.jpg"
    },
    {
        titulo: 'Coringa',
        descricao: "Coringa, lançado em 2019 e dirigido por Todd Phillips, conta a história de origem de Arthur Fleck, um comediante fracassado que se transforma no icônico vilão Coringa de Gotham City. O filme explora temas de saúde mental e desigualdade social, com uma performance aclamada de Joaquin Phoenix, que lhe rendeu o Oscar de Melhor Ator.",
        direcao: "Todd Phillips",
        Ano: "2019",
        Elenco: "Joaquin Phoenix (Arthur Fleck), Robert De Niro (Murray Franklin), Zazie Beetz (Sophie Dumond)",
        Roteiro: "Todd Phillips, Scott Silver",
        Gênero: "Drama, Crime, Thriller",
        Duração: "2:02:00 (122 minutos)",
        Prêmios: "Vencedor de 2 Oscars, incluindo Melhor Ator e Melhor Trilha Sonora",
        Bilheteria: "Aproximadamente $1.07 bilhões mundialmente",
        link: "https://www.imdb.com/title/tt7286456/",
        tags: "Joker, Joaquin Phoenix, Todd Phillips, DC Comics, Gotham, 2019 film, Crime drama, Oscar-winning movie, Arthur Fleck, Mental health",
        rating: "4.4/5",
        imagem: "img/coringa.jpg"
    },
    {
        titulo: 'Interestelar',
        descricao: "Interestelar, dirigido por Christopher Nolan e lançado em 2014, é um épico de ficção científica que segue um grupo de astronautas em busca de um novo lar para a humanidade. O filme explora temas de amor, sacrifício e a relação entre tempo e espaço, com visuais impressionantes e uma trilha sonora marcante de Hans Zimmer.",
        direcao: "Christopher Nolan",
        Ano: "2014",
        Elenco: "Matthew McConaughey (Cooper), Anne Hathaway (Brand), Jessica Chastain (Murph), Michael Caine (Professor Brand)",
        Roteiro: "Jonathan Nolan, Christopher Nolan",
        Gênero: "Ficção Científica, Aventura, Drama",
        Duração: "2:49:00 (169 minutos)",
        Prêmios: "Vencedor de 1 Oscar de Melhores Efeitos Visuais",
        Bilheteria: "Aproximadamente $701 milhões mundialmente",
        link: "https://www.imdb.com/title/tt0816692/",
        tags: "Interstellar, Christopher Nolan, Matthew McConaughey, Space travel, Sci-fi, Time dilation, Black hole, 2014 film, Epic, Hans Zimmer",
        rating: "4.3/5",
        imagem: "img/interstellar.jpg"
    },
    {
        titulo: 'Pulp Fiction: Tempo de Violência',
        descricao: "Pulp Fiction é um filme de 1994 dirigido por Quentin Tarantino, conhecido por sua narrativa não linear. O filme segue múltiplas histórias interconectadas sobre crime em Los Angeles, com personagens icônicos como Vincent Vega e Jules Winnfield. Pulp Fiction é considerado um marco do cinema e ajudou a definir o estilo de Tarantino.",
        direcao: "Quentin Tarantino",
        Ano: "1994",
        Elenco: "John Travolta (Vincent Vega), Samuel L. Jackson (Jules Winnfield), Uma Thurman (Mia Wallace)",
        Roteiro: "Quentin Tarantino, Roger Avary",
        Gênero: "Crime, Drama",
        Duração: "2:34:00 (154 minutos)",
        Prêmios: "Vencedor de 1 Oscar de Melhor Roteiro Original",
        Bilheteria: "Aproximadamente $213 milhões mundialmente",
        link: "https://www.imdb.com/title/tt0110912/",
        tags: "Pulp Fiction, Quentin Tarantino, John Travolta, Samuel L. Jackson, Uma Thurman, 1994 film, Crime drama, Non-linear storytelling, Cult classic, Oscar-winning movie",
        rating: "4.5/5",
        imagem: "img/pulpfiction.jpg"
    },
    {
        titulo: 'Matrix',
        descricao: "Matrix é um filme de ficção científica lançado em 1999 e dirigido pelas irmãs Wachowski. A trama segue Neo, um hacker que descobre que a realidade é uma simulação controlada por máquinas. O filme é amplamente aclamado por sua inovação em efeitos especiais, incluindo a técnica de 'bullet time'.",
        direcao: "Lana Wachowski, Lilly Wachowski",
        Ano: "1999",
        Elenco: "Keanu Reeves (Neo), Laurence Fishburne (Morpheus), Carrie-Anne Moss (Trinity)",
        Roteiro: "Lana Wachowski, Lilly Wachowski",
        Gênero: "Ficção Científica, Ação",
        Duração: "2:16:00 (136 minutos)",
        Prêmios: "Vencedor de 4 Oscars, incluindo Melhores Efeitos Visuais",
        Bilheteria: "Aproximadamente $466 milhões mundialmente",
        link: "https://www.imdb.com/title/tt0133093/",
        tags: "The Matrix, Keanu Reeves, Wachowskis, Sci-fi, Bullet time, Virtual reality, Action, 1999 film, Oscar-winning movie, Cult classic",
        rating: "4.6/5",
        imagem: "img/Matrix.jpg"
    },
    {
        titulo: 'Clube da Luta',
        descricao: "Clube da Luta, dirigido por David Fincher e lançado em 1999, é um filme que explora temas de alienação, consumismo e masculinidade. A história segue um homem comum que forma um clube de luta clandestino com um vendedor de sabão chamado Tyler Durden. O filme se tornou um clássico cult ao longo dos anos.",
        direcao: "David Fincher",
        Ano: "1999",
        Elenco: "Brad Pitt (Tyler Durden), Edward Norton (Narrador), Helena Bonham Carter (Marla Singer)",
        Roteiro: "Jim Uhls (baseado no romance de Chuck Palahniuk)",
        Gênero: "Drama",
        Duração: "2:19:00 (139 minutos)",
        Prêmios: "Indicado a 1 Oscar de Melhores Efeitos Sonoros",
        Bilheteria: "Aproximadamente $101 milhões mundialmente",
        link: "https://www.imdb.com/title/tt0137523/",
        tags: "Fight Club, David Fincher, Brad Pitt, Edward Norton, Cult classic, 1999 film, Anti-consumerism, Masculinity, Dark drama, Chuck Palahniuk",
        rating: "4.3/5",
        imagem: "img/fightclub.jpg"
    },
    {
        titulo: 'O Poderoso Chefão',
        descricao: "O Poderoso Chefão, dirigido por Francis Ford Coppola, é um dos filmes mais aclamados de todos os tempos. Lançado em 1972, o filme conta a história da família Corleone, uma das mais poderosas famílias mafiosas dos Estados Unidos. O filme explora temas de poder, família e traição.",
        direcao: "Francis Ford Coppola",
        Ano: "1972",
        Elenco: "Marlon Brando (Vito Corleone), Al Pacino (Michael Corleone), James Caan (Sonny Corleone)",
        Roteiro: "Mario Puzo, Francis Ford Coppola (baseado no romance de Mario Puzo)",
        Gênero: "Crime, Drama",
        Duração: "2:55:00 (175 minutos)",
        Prêmios: "Vencedor de 3 Oscars, incluindo Melhor Filme",
        Bilheteria: "Aproximadamente $245 milhões mundialmente",
        link: "https://www.imdb.com/title/tt0068646/",
        tags: "The Godfather, Francis Ford Coppola, Marlon Brando, Al Pacino, Mafia, Crime drama, Classic, 1972 film, Oscar-winning movie, Family saga",
        rating: "4.9/5",
        imagem: "img/thegodfather.jpg"
    },
    {
        titulo: 'A Origem',
        descricao: "A Origem, dirigido por Christopher Nolan e lançado em 2010, é um thriller de ficção científica que explora o conceito de invasão de sonhos. Leonardo DiCaprio interpreta Dom Cobb, um especialista em extrair segredos de dentro do subconsciente das pessoas durante o sono. O filme é conhecido por seu enredo complexo e visual inovador.",
        direcao: "Christopher Nolan",
        Ano: "2010",
        Elenco: "Leonardo DiCaprio (Dom Cobb), Joseph Gordon-Levitt (Arthur), Ellen Page (Ariadne)",
        Roteiro: "Christopher Nolan",
        Gênero: "Ficção Científica, Ação, Thriller",
        Duração: "2:28:00 (148 minutos)",
        Prêmios: "Vencedor de 4 Oscars, incluindo Melhores Efeitos Visuais",
        Bilheteria: "Mais de $830 milhões mundialmente",
        link: "https://www.imdb.com/title/tt1375666/",
        tags: "Inception, Christopher Nolan, Leonardo DiCaprio, Sci-fi, Dreams, Heist, Thriller, 2010 film, Visual effects, Oscar-winning movie",
        rating: "4.5/5",
        imagem: "img/inception.jpg"
    },
    {
        titulo: 'O Cavaleiro das Trevas',
        descricao: "O Cavaleiro das Trevas, dirigido por Christopher Nolan, é um filme de super-herói lançado em 2008. O filme segue Batman enfrentando o vilão Coringa em uma batalha pelo destino de Gotham City. A performance de Heath Ledger como o Coringa foi amplamente aclamada, rendendo-lhe um Oscar póstumo.",
        direcao: "Christopher Nolan",
        Ano: "2008",
        Elenco: "Christian Bale (Bruce Wayne/Batman), Heath Ledger (Coringa), Aaron Eckhart (Harvey Dent)",
        Roteiro: "Jonathan Nolan, Christopher Nolan",
        Gênero: "Ação, Crime, Drama",
        Duração: "2:32:00 (152 minutos)",
        Prêmios: "Vencedor de 2 Oscars, incluindo Melhor Ator Coadjuvante (Heath Ledger)",
        Bilheteria: "Mais de $1 bilhão mundialmente",
        link: "https://www.imdb.com/title/tt0468569/",
        tags: "The Dark Knight, Batman, Christopher Nolan, Heath Ledger, Christian Bale, DC Comics, Superhero, 2008 film, Oscar-winning movie, Gotham City",
        rating: "4.7/5",
        imagem: "img/thedarkknight.jpg"
    },
    {
        titulo: 'O Senhor dos Anéis: O Retorno do Rei',
        descricao: "O Senhor dos Anéis: O Retorno do Rei, lançado em 2003 e dirigido por Peter Jackson, é o capítulo final da trilogia baseada nos livros de J.R.R. Tolkien. O filme segue a batalha final pela Terra-média enquanto Frodo se aproxima de destruir o Anel. O filme é amplamente elogiado e venceu 11 Oscars.",
        direcao: "Peter Jackson",
        Ano: "2003",
        Elenco: "Elijah Wood (Frodo), Viggo Mortensen (Aragorn), Ian McKellen (Gandalf)",
        Roteiro: "Fran Walsh, Philippa Boyens, Peter Jackson (baseado no romance de J.R.R. Tolkien)",
        Gênero: "Aventura, Fantasia, Drama",
        Duração: "3:21:00 (201 minutos)",
        Prêmios: "Vencedor de 11 Oscars, incluindo Melhor Filme e Melhor Diretor",
        Bilheteria: "Mais de $1.1 bilhão mundialmente",
        link: "https://www.imdb.com/title/tt0167260/",
        tags: "The Lord of the Rings, Return of the King, Peter Jackson, Elijah Wood, J.R.R. Tolkien, Fantasy, Epic, 2003 film, Oscar-winning movie, Middle-earth",
        rating: "4.8/5",
        imagem: "img/returnoftheking.jpg"
    },
    {
        titulo: 'Gladiador',
        descricao: "Gladiador é um épico histórico lançado em 2000, dirigido por Ridley Scott. O filme conta a história de Maximus, um general romano que é traído e forçado a se tornar um gladiador. O filme é conhecido por suas cenas de batalha e a performance de Russell Crowe, que lhe rendeu um Oscar de Melhor Ator.",
        direcao: "Ridley Scott",
        Ano: "2000",
        Elenco: "Russell Crowe (Maximus), Joaquin Phoenix (Commodus), Connie Nielsen (Lucilla)",
        Roteiro: "David Franzoni, John Logan, William Nicholson",
        Gênero: "Ação, Aventura, Drama",
        Duração: "2:35:00 (155 minutos)",
        Prêmios: "Vencedor de 5 Oscars, incluindo Melhor Filme e Melhor Ator (Russell Crowe)",
        Bilheteria: "Aproximadamente $457 milhões mundialmente",
        link: "https://www.imdb.com/title/tt0172495/",
        tags: "Gladiator, Ridley Scott, Russell Crowe, Roman Empire, Epic, 2000 film, Historical drama, Oscar-winning movie, Action, Joaquin Phoenix",
        rating: "4.6/5",
        imagem: "img/gladiator.jpg"
    },
    {
        titulo: 'Parasita',
        descricao: "Parasita, dirigido por Bong Joon-ho e lançado em 2019, é um thriller de comédia sombria que explora as desigualdades sociais na Coreia do Sul. A trama segue a família Kim, que se infiltra na vida de uma família rica, os Parks. O filme fez história ao se tornar o primeiro filme estrangeiro a ganhar o Oscar de Melhor Filme.",
        direcao: "Bong Joon-ho",
        Ano: "2019",
        Elenco: "Song Kang-ho (Kim Ki-taek), Lee Sun-kyun (Park Dong-ik), Cho Yeo-jeong (Park Yeon-gyo)",
        Roteiro: "Bong Joon-ho, Han Jin-won",
        Gênero: "Drama, Comédia, Thriller",
        Duração: "2:12:00 (132 minutos)",
        Prêmios: "Vencedor de 4 Oscars, incluindo Melhor Filme e Melhor Diretor",
        Bilheteria: "Aproximadamente $263 milhões mundialmente",
        link: "https://www.imdb.com/title/tt6751668/",
        tags: "Parasite, Bong Joon-ho, South Korea, Class struggle, 2019 film, Oscar-winning movie, Dark comedy, Thriller, Foreign film, Social commentary",
        rating: "4.6/5",
        imagem: "img/parasite.jpg"
    }
    
    
];

